### ISSUE TITLE
Add some improvements for carousel's buttons

### ISSUE THREAD

**Issue by zuozas** [ergoplatform/sigmaverse#73]
#### What should be done

- [ ] Add hover state. On hover button should get #303030 background color;
- [ ] Update default state color. The new default color should be #202020;
- [ ] Update progress line color. It should use the same hover state color #303030;
- [ ] Remove easing transition for the progress bar. It should be linear without any jumping at the start and slowing down at the end;

#### Quick preview of all states

<img width="357" alt="CleanShot 2022-03-28 at 17 15 13@2x" src="https://user-images.githubusercontent.com/4293555/160442032-0358a3fa-fa11-4db4-a57b-346c0a5e7200.png">

#### Figma link -
https://www.figma.com/file/7MohdRwL3Cu4H8c4udzsfu/Sigmaverse-2.0?node-id=15%3A772
